Add PSP support
NagyD/SDLPoP pull request #319
Opened 2024-08-15 21:25 UTC by vichoca9

The main issue with PSP was the crashes due to misaligned data. Now it works, but some issues were avoided in order for it to work (ini_process_word and such). Tested on real hardware (psp 2004 slim).

2024-08-16 07:22 UTC, sharkwouter requested changes
I had some suggestions, biut cool you got this running. We should take a look at why the you're getting crashes from the existing code. Some of these things may be related to us using gcc 14, which would mean easy fixes are available. Otherwise there might be some bugs in the PSPDEV sdk, we'll have to look into it.

2024-08-16 07:22 UTC, sharkwouter commented on src/CMakeLists.txt
>  else() # Linux, *BSD, etc.
I would keep this else and use `elseif(PSP)`

2024-08-16 07:22 UTC, sharkwouter commented on src/CMakeLists.txt
> +    )
I would use pkgconf here, making is much more readable
```suggestion
include(FindPkgConfig)
pkg_search_module(SDL2 REQUIRED sdl2)

target_include_directories(target PRIVATE ${SDL2_INCLUDE_DIRS})

target_link_libraries(target PRIVATE
    ${SDL2_LIBRARIES}
)
```

2024-08-16 07:22 UTC, sharkwouter commented on src/types.h
> +#endif
This look out of place

2024-08-16 07:22 UTC, sharkwouter commented on src/seg009.c
> +//#if  defined(USE_COMPAT_TIMER) || defined(__PSP__)
This seems off

2024-08-18 19:06 UTC, sharkwouter commented on src/CMakeLists.txt
> +find_package(SDL2 REQUIRED)
```suggestion
```

2024-11-05 20:12 UTC, Apaczer commented
I get similar errors on LittleEndian ARM 32bit platform, solved now tks. I only had remove implicit conversion of `word` and not use label in statement. BTW "pointer cast crash" is usual here either 🙃

2025-04-20 16:17 UTC, merged